#not use now
amcl:
  min_particles: 100
  max_particles: 2000
  update_min_d: 0.2
  update_min_a: 0.5
  laser_min_range: 0.0
  laser_max_range: 30.0
  odom_model_type: 'diff'
  odom_alpha1: 0.2
  odom_alpha2: 0.2
  odom_alpha3: 0.2
  odom_alpha4: 0.2
  laser_z_hit: 0.5
  laser_z_short: 0.05
  laser_z_max: 0.05
  laser_z_rand: 0.5
  laser_likelihood_max_dist: 2.0
  initial_pose_x: 0.0
  initial_pose_y: 0.0
  initial_pose_a: 0.0
  transform_tolerance: 0.1

