TrajectoryPlannerROS:
  max_vel_x: 0.035 #0.45
  min_vel_x: -0.035 #0.1

  max_vel_theta: 0.07 #1.0
  min_vel_theta: 0.035 #0.4
  
  max_vel_trans:  0.07
  min_vel_trans:  0.035
  min_in_place_vel_theta: 0.4

  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  
  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 1.57
  
  holonomic_robot: false

