TrajectoryPlannerROS:
  max_vel_x: 0.07 #0.45
  min_vel_x: 0 #0.1

  max_vel_theta: 0.14 #1.0
  min_vel_theta: 0 #0.4
  
  max_vel_trans:  0.14
  min_vel_trans:  0
  min_in_place_vel_theta: 0.4

  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.08
  latch_xy_goal_tolerance: false

# Differential-drive robot configuration
  holonomic_robot: false
  controller_frequency: 10

  sim_time: 1.0
  vx_samples: 3
  vtheta_samples: 20