DWAPlannerROS:
# Robot Configuration Parameters
  max_vel_x: 0.035 #0.45
  min_vel_x: -0.035 #0.1

  max_vel_theta: 0.07 #1.0
  min_vel_theta: 0.035 #0.4
  
  max_vel_trans:  0.07
  min_vel_trans:  0.035
  min_in_place_vel_theta: 0.4

  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.0349066 #0.15

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 5 #0.8
  vx_samples: 18
  vth_samples: 20
  sim_granularity: 0.05

# Trajectory Scoring Parameters
  path_distance_bias: 60.0      # 32.0   - weighting for how much it should stick to the global path plan
  goal_distance_bias: 24
  stop_time_buffer: 0.2

# Global Plan Parameters
  prune_plan: false #true

  controller_frequency: 30