local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 5
  publish_frequency: 3
  transform_tolerance: 8

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  